### ISSUE TITLE
Heuristic agent Dynamic partition

### ISSUE THREAD

**Issue by shihju** [hongzimao/decima-sim#14]
Is dynamic partition agent (class DynamicPartitionAgent) in the repository related to the dynamic-resource-allocation scheduler from spark? Are they the same thing? If not, what is this dynamic partition agent? http://spark.apache.org/docs/2.2.1/job-scheduling.html#dynamic-resource-allocation

**Comment by hongzimao** [comment]
It's designed with a similar underlying principle as the dynamic-resource-allocation scheduler from spark --- i.e., all jobs equally divide the cluster resource at any point in time. However, the default dynamic-resource-allocation didn't give us fine-grained enough resource sharing (e.g., the executor doesn't immediately flow to other jobs when finishing a _last_ stage of a job). Another reason is we want to implement a heuristic agent using the same environment as the learning agent. 

In our paper, this dynamic partition agent is described as the "fair" agent (section 7.1 point (3), figure 3(c)). Hope this helps!

**Comment by shihju** [comment]
Thank you, it helped a lot.
