### ISSUE TITLE
Training process is too slow

### ISSUE THREAD

**Issue by OptimusPrime1997** [hongzimao/decima-sim#21]
Hi, I run your code with the example on the readme. But every epoch cost 30+s running on CPU. When I use GPU run the same code, it costs 160+s! In your paper, every epoch cost 1.5s rougly. How can I reduce the trainning time.
My environment as following:
Intel  8180M 2.5GHz (112 core)
Tesla V100 x 2
Ubuntu18.04+Nvidia driver410.48+Cuda10.0.130+libcudnn7.6.5+tensorflow1.15
I set allow_growth=True of tf.config to avoid OOM error.
I want to reproduce your experiments. How to accelerate the process except reducing the size of workload?
Thank you!

**Comment by hongzimao** [comment]
Thanks for carefully reading our paper. The 1.5 sec is for the very initial training rounds in the curriculum learning process (section 5.3 challenge 1, presentation slides 22 - 25). For simplicity the training code here didn't start with the very short episode length. You can reduce the initial episode length by reducing `num_stream_jobs_grow` (curriculum learning is also controlled by `reset_prob`, `reset_prob_decay`, `reset_prob_min`, `num_stream_jobs_grow ` and `num_stream_jobs_max `)

Nonetheless, ~30s per round checks out with what we observed for this codebase. In our experience 200 iterations should give you something better than the baseline schemes (we usually let the program run overnight). Here's an example trained model #12

The 160s GPU time is a little weird. We observed GPU runtime to be on par with the CPU time. Honestly we didn't optimize the code efficiency that much (we just made sure the basics like the device memory should be enough to hold all the sparse matrix for GNN). If you find ways to optimize the code in any way, please do let use know! We can include your update in a pull request. Thanks!

**Comment by hongzimao** [comment]
Thanks for carefully reading our paper. The 1.5 sec is for the very initial training rounds in the curriculum learning process (section 5.3 challenge 1, presentation slides 22 - 25). For simplicity the training code here didn't start with the very short episode length. You can reduce the initial episode length by reducing `num_stream_jobs ` (curriculum learning is also controlled by `reset_prob`, `reset_prob_decay`, `reset_prob_min`, `num_stream_jobs_grow ` and `num_stream_jobs_max`)

Nonetheless, ~30s per round checks out with what we observed for this codebase. In our experience 200 iterations (~16 hours) should give you something better than the baseline schemes (we usually let the program run overnight). Here's an example trained model #12

The 160s GPU time is a little weird. We observed GPU runtime to be on par with the CPU time. Honestly we didn't optimize the code efficiency that much (we just did the basic things like making sure the device memory is enough to hold all the sparse matrices for GNNs). If you find ways to optimize the code in any method, please do let use know! We can perhaps include your update in a pull request. Thanks!
