### ISSUE TITLE
State information and features

### ISSUE THREAD

**Issue by larissayukimiz** [hongzimao/decima-sim#22]
Hi,
In Section 5.1, you talk about Decima converting the state information into features. Are the features always those in the image?
![node-attributes](https://user-images.githubusercontent.com/60020710/92638522-6324b900-f2a8-11ea-9353-5d4c878e7b29.png)

**Comment by larissayukimiz** [comment]
Also what's the dimension of the per-node embedding? What do you mean by R¹⁶?

**Comment by hongzimao** [comment]
You found the right place where we initialize the features for the nodes. Note that these features can get updated at each scheduling interaction. You can search for the names in the code space and see how they get called. For example, `num_finished_tasks` is updated here https://github.com/hongzimao/decima-sim/blob/c010dd74ff4b7566bd0ac989c90a32cfbc630d84/spark_env/env.py#L266. 

The main agent interaction loop is https://github.com/hongzimao/decima-sim/blob/c010dd74ff4b7566bd0ac989c90a32cfbc630d84/train.py#L165, where the model is inovked in  https://github.com/hongzimao/decima-sim/blob/c010dd74ff4b7566bd0ac989c90a32cfbc630d84/train.py#L28-L36. You can see the features are parsed here (then they go into the policy network described in Figure 6 of the paper): https://github.com/hongzimao/decima-sim/blob/c010dd74ff4b7566bd0ac989c90a32cfbc630d84/actor_agent.py#L468-L472.

As in the paper, R^16 is the dimension of each vector of the (example) node feature. It just means there are 16 real numbers.
