### ISSUE TITLE
Gorot method

### ISSUE THREAD

**Issue by larissayukimiz** [hongzimao/decima-sim#24]
![2020-09-28_18-17](https://user-images.githubusercontent.com/60020710/94491806-ef930f00-01b6-11eb-9522-e0695d4eaf01.png)

Hi!
I'd like to know why you use _output_dims_ as the fan-in in f's and g's (at the Gorot method). I mean, why not use, as the fan-in, hid_dims and as the fan-out, the output_dims?

**Comment by hongzimao** [comment]
Good question. Notice that the GNN structure (loosely) is h -> f -> g. So the dimensions in the connections are input_dim -> ouput_dim (kind of like a "hidden_dim") -> output_dim -> output_dim. The "hidden_dim" should not be confused with `self.hid_dims`, which is within each h, f, g. You can track how h, f, g are actually used by searching when `prep` `proc` and `agg` are called. Hope this helps!
