### ISSUE TITLE
Past workload logs

### ISSUE THREAD

**Issue by larissayukimiz** [hongzimao/decima-sim#25]
Hi!

Just had a doubt about what you meant in "Decima uses existing monitoring information and **past workload logs** to automatically learn sophisticated scheduling policies". By "past workload logs", you're talking about the fact that agent learns as he receives rewards, right?

**Comment by hongzimao** [comment]
You are right. In this sentence in the intro of the paper, we basically wanted to say "RL trains based on the experience data from interacting with a cluster scheduler".
