### ISSUE TITLE
About nodes information

### ISSUE THREAD

**Issue by jsw7460** [hongzimao/decima-sim#33]
Hello. Thank you for giving an interesting model DECIMA.

How can I get a feature vector of a node in job DAG : In the paper it consists of
(i) : # of tasks remaining in the stage
(ii) : The average task duration
(iii) : The number of executors currently working
(iv) :  The number of available executors.
(v) : Whether available executors are local to the job.

**Comment by hongzimao** [comment]
You can follow the process in `test.py`. The environment gives observation in https://github.com/hongzimao/decima-sim/blob/master/test.py#L61, the agent uses the observation in https://github.com/hongzimao/decima-sim/blob/master/test.py#L67, the observation is translated into vector form and passed through the policy neural network in https://github.com/hongzimao/decima-sim/blob/master/actor_agent.py#L513-L520. Hope this helps!
