### ISSUE TITLE
Some questions about Decima's GNN

### ISSUE THREAD

**Issue by zhangy0822** [hongzimao/decima-sim#37]
I recently learned this code (gcn-pytorch). Is this part mainly to implement equation 1 in Decima paper?

According to the Decima paper, does the message passing go from leaf to root? The DAG Summary is then computed based on all the nodes in a job. The GCNCov layer in PyTorch Geometric seems to calculate only one massage passing from neighbor nodes, not from leaf to root. I don't know if that's a major part of the message passing scheme that you have designed.

I have another problem that has been puzzling me. What is the significance of 'num_steps' in gcn-pytorch? Is it the same as' max_depth 'in the TensorFlow code? Does it represent the maximum number of message passing from leave to root? How does he control it in training?

I look forward to your reply. Thank you

**Comment by hongzimao** [comment]
Thanks for your questions.

Re message passing: in our problem, the jobs modeled as directed graphs (child stages cannot run until all parent stages have completed). Passing message from leaves (child stages) to roots (parent stages) have natural meaning - an agent wants to plan ahead and take into account all child stages when deciding to schedule a parent stage. For general pytorch geometric library, my understanding is their generic underlying graph is undirected or bidirectional (e.g., chemical structures, social networks).

Re num_steps/max_depth: I think your understanding is correct. It controls the maximum number of hops a message can traverse in the graph. For example, a single chain graph with 5 nodes A -> B -> C -> D -> E, if the max_depth is 3, then the information encoded in leaf E can traverse up to node B.

Hope these help!

**Comment by zhangy0822** [comment]
Thank you very much for your help.
